;############################################################################
;# Datove structury a promenne waits - hodnoty pro casove smycky...
;############################################################################

Loop_Wait_Delay_001s  DD 0   ;1 sekunda
Loop_Wait_Delay_100ms DD 0   ;100 milisekund
Loop_Wait_Delay_010ms DD 0   ;10 milisekund
Loop_Wait_Delay_001ms DD 0   ;1 milisekunda
Loop_Wait_Delay_062us DD 0   ;62 mikrosekund... asi nejmenci :)


