;#################################################################################
;# 16-ti bitove includy
;#################################################################################
       Include  .\..\inc\code\code16\initdscr.inc
       Include  .\..\inc\code\code16\A20.inc
       Include  .\..\inc\code\code16\t00ls-16.inc
       Include  .\..\inc\code\code16\procesor.inc
       Include  .\..\inc\code\code16\textmod.inc
       Include  .\..\inc\code\code16\panic-16.inc