TSKMM_Alloc_B                          equ  00000000
TSKMM_Dealloc                          equ  00000001
Alloc_shared_memory                    equ  00000002   (Booh Only)
Alloc_fyslin_memory                    equ  00000003   (Booh Only)
Alloc_taskman_memory                   equ  00000004   (Booh Only)
DeAlloc                                equ  00000005   (Booh Only)
Memory_Manager_Create_CallGate         equ  00000006   (Booh Only)
