;############################################################################
;# Memory Manager for Nothing
;############################################################################

Include .\..\inc\code\code32\MEM\alloc.inc
Include .\..\inc\code\code32\MEM\desc.inc
Include .\..\inc\code\code32\MEM\mm.inc
Include .\..\inc\code\code32\MEM\tss_ldt.inc
Include .\..\inc\code\code32\MEM\memdet.inc
Include .\..\inc\code\code32\MEM\MEM-TSK\memtsk.inc
Include .\..\inc\code\code32\MEM\MEM-TSK\desctsk.inc
Include .\..\inc\code\code32\MEM\MEM-TSK\alloctsk.inc
